"""forget password fields

Revision ID: 2a64b8570afc
Revises: c58bc1361174
Create Date: 2026-04-02 07:12:41.805079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a64b8570afc'
down_revision: Union[str, Sequence[str], None] = 'c58bc1361174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_user', sa.Column('password_reset_jti_hash', sa.String(length=64), nullable=True))
    op.add_column('account_user', sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True))
    op.alter_column('account_user', 'role',
               existing_type=postgresql.ENUM('STUDENT', 'ALUMNI', 'ADMIN', name='user_role'),
               nullable=True)
    op.create_index(op.f('ix_account_user_password_reset_expires_at'), 'account_user', ['password_reset_expires_at'], unique=False)
    op.create_index(op.f('ix_account_user_password_reset_jti_hash'), 'account_user', ['password_reset_jti_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_password_reset_jti_hash'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_password_reset_expires_at'), table_name='account_user')
    op.alter_column('account_user', 'role',
               existing_type=postgresql.ENUM('STUDENT', 'ALUMNI', 'ADMIN', name='user_role'),
               nullable=False)
    op.drop_column('account_user', 'password_reset_expires_at')
    op.drop_column('account_user', 'password_reset_jti_hash')
    # ### end Alembic commands ###
