"""move preferred_name

Revision ID: 4847bbf22c80
Revises: 9a264b0d00f5
Create Date: 2026-01-27 02:28:40.397962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4847bbf22c80'
down_revision: Union[str, Sequence[str], None] = '9a264b0d00f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni_profile', sa.Column('preferred_name', sa.String(length=100), nullable=True))
    op.drop_column('student_profile', 'preferred_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profile', sa.Column('preferred_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('alumni_profile', 'preferred_name')
    # ### end Alembic commands ###
