"""add skills field

Revision ID: 5cf03508e810
Revises: 4847bbf22c80
Create Date: 2026-02-16 07:27:05.460510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cf03508e810'
down_revision: Union[str, Sequence[str], None] = '4847bbf22c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumni_profile', sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('student_profile', sa.Column('location', sa.String(length=120), nullable=True))
    op.add_column('student_profile', sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profile', 'skills')
    op.drop_column('student_profile', 'location')
    op.drop_column('alumni_profile', 'skills')
    # ### end Alembic commands ###
