"""add email verification

Revision ID: 9a264b0d00f5
Revises: 8b555ef5a9f0
Create Date: 2026-01-23 03:30:32.025439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a264b0d00f5'
down_revision: Union[str, Sequence[str], None] = '8b555ef5a9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_user', sa.Column('verify_jti_hash', sa.String(length=64), nullable=True))
    op.add_column('account_user', sa.Column('verify_expires_at', sa.DateTime(), nullable=True))
    op.add_column('account_user', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_account_user_verified_at'), 'account_user', ['verified_at'], unique=False)
    op.create_index(op.f('ix_account_user_verify_expires_at'), 'account_user', ['verify_expires_at'], unique=False)
    op.create_index(op.f('ix_account_user_verify_jti_hash'), 'account_user', ['verify_jti_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_verify_jti_hash'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_verify_expires_at'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_verified_at'), table_name='account_user')
    op.drop_column('account_user', 'verified_at')
    op.drop_column('account_user', 'verify_expires_at')
    op.drop_column('account_user', 'verify_jti_hash')
    # ### end Alembic commands ###
