"""init tables

Revision ID: e3f5016525a0
Revises: 
Create Date: 2026-01-23 00:31:11.138895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3f5016525a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_user',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'ALUMNI', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('last_password_reset_request', sa.DateTime(), nullable=True),
    sa.Column('last_activation_email_sent', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_account_user_created_at'), 'account_user', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_user_deleted_at'), 'account_user', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_account_user_email'), 'account_user', ['email'], unique=True)
    op.create_index(op.f('ix_account_user_last_login_at'), 'account_user', ['last_login_at'], unique=False)
    op.create_index(op.f('ix_account_user_updated_at'), 'account_user', ['updated_at'], unique=False)
    op.create_table('account_identity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('provider_sub', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('provider_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['account_user.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_sub'),
    sa.UniqueConstraint('user_uid', 'provider')
    )
    op.create_index(op.f('ix_account_identity_created_at'), 'account_identity', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_identity_provider'), 'account_identity', ['provider'], unique=False)
    op.create_index(op.f('ix_account_identity_provider_sub'), 'account_identity', ['provider_sub'], unique=False)
    op.create_index(op.f('ix_account_identity_user_uid'), 'account_identity', ['user_uid'], unique=False)
    op.create_table('admin_profile',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['account_user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('alumni_profile',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('pronouns', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('avatar_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('avatar_updated_at', sa.DateTime(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('work_duration_months', sa.Integer(), nullable=True),
    sa.Column('academic_history', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('graduated_from', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('graduated_at_year', sa.Integer(), nullable=True),
    sa.Column('linkedin', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('personal_website', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('company_website', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['account_user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_alumni_profile_avatar_updated_at'), 'alumni_profile', ['avatar_updated_at'], unique=False)
    op.create_index(op.f('ix_alumni_profile_first_name'), 'alumni_profile', ['first_name'], unique=False)
    op.create_index(op.f('ix_alumni_profile_last_name'), 'alumni_profile', ['last_name'], unique=False)
    op.create_table('refresh_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['account_user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_session_created_at'), 'refresh_session', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_session_expires_at'), 'refresh_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_session_replaced_by'), 'refresh_session', ['replaced_by'], unique=False)
    op.create_index(op.f('ix_refresh_session_revoked_at'), 'refresh_session', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_session_token_hash'), 'refresh_session', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_session_user_uid'), 'refresh_session', ['user_uid'], unique=False)
    op.create_table('student_profile',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('preferred_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('pronouns', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('avatar_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('avatar_updated_at', sa.DateTime(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('major', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('university', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('school_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('alumni_to_be', sa.Boolean(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('linkedin', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('personal_website', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('promoted_to_alumni_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['account_user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_student_profile_avatar_updated_at'), 'student_profile', ['avatar_updated_at'], unique=False)
    op.create_index(op.f('ix_student_profile_first_name'), 'student_profile', ['first_name'], unique=False)
    op.create_index(op.f('ix_student_profile_last_name'), 'student_profile', ['last_name'], unique=False)
    op.create_index(op.f('ix_student_profile_promoted_to_alumni_at'), 'student_profile', ['promoted_to_alumni_at'], unique=False)
    op.create_index(op.f('ix_student_profile_school_email'), 'student_profile', ['school_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profile_school_email'), table_name='student_profile')
    op.drop_index(op.f('ix_student_profile_promoted_to_alumni_at'), table_name='student_profile')
    op.drop_index(op.f('ix_student_profile_last_name'), table_name='student_profile')
    op.drop_index(op.f('ix_student_profile_first_name'), table_name='student_profile')
    op.drop_index(op.f('ix_student_profile_avatar_updated_at'), table_name='student_profile')
    op.drop_table('student_profile')
    op.drop_index(op.f('ix_refresh_session_user_uid'), table_name='refresh_session')
    op.drop_index(op.f('ix_refresh_session_token_hash'), table_name='refresh_session')
    op.drop_index(op.f('ix_refresh_session_revoked_at'), table_name='refresh_session')
    op.drop_index(op.f('ix_refresh_session_replaced_by'), table_name='refresh_session')
    op.drop_index(op.f('ix_refresh_session_expires_at'), table_name='refresh_session')
    op.drop_index(op.f('ix_refresh_session_created_at'), table_name='refresh_session')
    op.drop_table('refresh_session')
    op.drop_index(op.f('ix_alumni_profile_last_name'), table_name='alumni_profile')
    op.drop_index(op.f('ix_alumni_profile_first_name'), table_name='alumni_profile')
    op.drop_index(op.f('ix_alumni_profile_avatar_updated_at'), table_name='alumni_profile')
    op.drop_table('alumni_profile')
    op.drop_table('admin_profile')
    op.drop_index(op.f('ix_account_identity_user_uid'), table_name='account_identity')
    op.drop_index(op.f('ix_account_identity_provider_sub'), table_name='account_identity')
    op.drop_index(op.f('ix_account_identity_provider'), table_name='account_identity')
    op.drop_index(op.f('ix_account_identity_created_at'), table_name='account_identity')
    op.drop_table('account_identity')
    op.drop_index(op.f('ix_account_user_updated_at'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_last_login_at'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_email'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_deleted_at'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_created_at'), table_name='account_user')
    op.drop_table('account_user')
    # ### end Alembic commands ###
